### ISSUE TITLE
Not able to make the test project work

### ISSUE THREAD

**Issue by erikaxel** [logtail/logtail-ruby-rails#27]
Hi,

It seems like the example application doesnt work out of the box.

**To reproduce:**
- Clone the repo
- Go to `example-project`
- Insert key into `config/application.rb`
- `bundle install && rails s`
- Open up localhost and click the "lets go" button

**Expected result**
Logs appearing in BetterStack

**Actual result**
No logs appearing

However, I did get some logs initially due to an exception in the application. I tried to access it via a local dev host alias I have, and then Rails by default spits out an exception which was sent to BetterStack: `[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: my.local.dev` 

So it seems like the key is correct and some of the setup works at least, but not the main logging test.

**Comment by PetrHeinz** [comment]
Hi @erikaxel and thanks for bringing this up 🙌 

I've managed to reproduce the issue, so I should be able to track it down and fix it tomorrow.

**Comment by PetrHeinz** [comment]
It seems to be an issue with `logtail-rack` in `v0.2.3`, when locking version at `0.2.2` it behaves correctly.

**Comment by PetrHeinz** [comment]
🔧 I've fixed the underlying issue in `logtail-rack` gem (https://github.com/logtail/logtail-ruby-rack/issues/12) 

Just upgrade to `v0.2.4` via `bundle update logtail-rack` and everything should be working correctly 🙂

Thanks again for reporting the issue 🙏
