### ISSUE TITLE
logtail-rails 0.2.5 is incompatible with Rails < 7.1

### ISSUE THREAD

**Issue by olivier-thatch** [logtail/logtail-ruby-rails#34]
Specifically, this check: https://github.com/logtail/logtail-ruby-rails/blob/21f750c33b7fe094a46b6da903e351b885e5c98c/lib/logtail-rails/logger.rb#L21

fails with Rails < 7.1 because `::ActiveSupport::BroadcastLogger` does not exist. You probably want to add a `defined?()` guard to the check.

**Comment by curusarn** [comment]
Hi @olivier-thatch,

Thank you for raising this.

I'm passing this on to the team to get fixed soon.
We'll make sure to post any updates here on GitHub.

Tanks again for reaching out!

**Comment by PetrHeinz** [comment]
Thanks again @olivier-thatch for reporting this 🙌 

Fixed in [logtail-rails 0.2.6](https://rubygems.org/gems/logtail-rails/versions/0.2.6).

**Comment by olivier-thatch** [comment]
Thanks for the quick fix!
