### ISSUE TITLE
Wrong number of arguments (given 2, expected 0..1)

### ISSUE THREAD

**Issue by leoplct** [logtail/logtail-ruby-rails#38]
I have just installed the gem and got this error

`Rails.logger.error("Something bad happened.")`

-> This works!

```
Rails.logger.warn("Log message wih structured logging.", {
    item: "Orange Soda",
    price: 100.00
})
```

/.rbenv/versions/3.2.2/lib/ruby/3.2.0/logger.rb:700:in `warn': wrong number of arguments (given 2, expected 0..1) (ArgumentError)

ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin23]

gem 'rails', '7.1.2'
logtail-rails (0.2.6)

**Comment by leoplct** [comment]
SOLVED: 

It was caused by having another logger in enviroment/development.rb
`config.logger     = ActiveSupport::Logger.new(STDOUT) `

I would recommend adding in the doc to check in all environments for existing code.

**Comment by curusarn** [comment]
Hi @leoplct!

I'm happy that you managed to solve the issue. Thanks for the suggestion!
