### ISSUE TITLE
How to filter sensitive headers from logs?

### ISSUE THREAD

**Issue by delphaber** [logtail/logtail-ruby-rails#9]
I'm evaluating the product ATM. I see that in the live view, under `event.http_request_received.headers_json` I can see all request's headers. The problem is that these headers might contain sensitive data, like access tokens. 

I've configured Rails with the right set of `Rails.application.config.filter_parameters`, but I can still see the access token in plain text in the logs.

Is there a way to stop sending request headers to Logtail?

Thanks!

**Comment by delphaber** [comment]
any news on this? :(

**Comment by curusarn** [comment]
Hi @delphaber,

Sorry for the delay. Thank you for reaching out.

We are tracking this issue internally. I don't have a time estimate to share, but I will make sure to keep you updated.

Thank you for your patience. 🙏

**Comment by beydogan** [comment]
This is the only reason we are not migrating to the logtail in our team right now.
